// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SingleCpu } from "./SingleCpu";

export interface CpuStat { cpu: SingleCpu, cpus: Array<SingleCpu>, }