// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SingleCpu { user: number, nice: number, system: number, idle: number, iowait: number, irq: number, softirq: number, steal: number, guest: number, guestNice: number, }