// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CpuStat } from "./CpuStat";

export interface Sium { sium: number, testt: string, cpu: CpuStat, }